/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 tech-console.gltf --transform 
Files: tech-console.gltf [41.54MB] > tech-console-transformed.glb [415.64KB] (99%)
Author: pawuwa (https://sketchfab.com/pawuwa)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/technology-console-c2ed8d4fb9dd4d8186a22ff2399ec171
Title: Technology console
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/tech-console-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/tech-console-transformed.glb");
